# -*- coding: utf-8 -*-
"""
/***************************************************************************
 sartracker
                                 A QGIS plugin
 SAR Tracking Console for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Donal O' Callaghan
        email                : ocallaghandonal2@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, QTimer
from qgis.PyQt.QtGui import QIcon, QFont
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QMessageBox, QLabel, QDialog, QVBoxLayout, QHBoxLayout, QPushButton
from qgis.core import (
    QgsCoordinateReferenceSystem, QgsCoordinateTransform,
    QgsProject, QgsPointXY, QgsRectangle, QgsApplication
)

# Initialize Qt resources from file resources.py
from .resources import *
import os.path
import traceback

# Import Qt5/Qt6 compatible constants and functions
from .utils.qt_compat import RightDockWidgetArea, dialog_exec, DialogAccepted
from .utils.notify import info, warning, error, success
from .utils.error_handler import ErrorHandler
from .utils.exceptions import SARTrackerError
from .utils.dialog_utils import BaseDialog

# Import our SAR tracking components with individual error tracking
# This allows us to detect and report exactly which imports fail, preventing
# cryptic crashes later in initGui() when attempting to use undefined classes.

# Module-level tracking of import failures (checked in initGui)
_import_errors = []
_imports_ok = True

# Import Provider Registry and trigger provider self-registration
try:
    from .providers.registry import registry as provider_registry
    from .providers.base import Provider
    # Trigger provider registration by importing them
    from .providers import csv, http_traccar
    # Note: provider_registry now contains registered providers (csv, http_traccar)
except Exception as e:
    _imports_ok = False
    _import_errors.append(('providers', e, traceback.format_exc()))
    provider_registry = None
    Provider = None
    print(f"ERROR importing providers: {e}")

# Import LayersController
try:
    from .controllers.layers_controller import LayersController
except Exception as e:
    _imports_ok = False
    _import_errors.append(('controllers.layers_controller.LayersController', e, traceback.format_exc()))
    LayersController = None
    print(f"ERROR importing LayersController: {e}")

# Import SARPanel
try:
    from .ui.sar_panel import SARPanel
except Exception as e:
    _imports_ok = False
    _import_errors.append(('ui.sar_panel.SARPanel', e, traceback.format_exc()))
    SARPanel = None
    print(f"ERROR importing SARPanel: {e}")

# Import MarkerMapTool
try:
    from .maptools.marker_tool import MarkerMapTool
except Exception as e:
    _imports_ok = False
    _import_errors.append(('maptools.marker_tool.MarkerMapTool', e, traceback.format_exc()))
    MarkerMapTool = None
    print(f"ERROR importing MarkerMapTool: {e}")

# Import MeasureTool
try:
    from .maptools.measure_tool import MeasureTool
except Exception as e:
    _imports_ok = False
    _import_errors.append(('maptools.measure_tool.MeasureTool', e, traceback.format_exc()))
    MeasureTool = None
    print(f"ERROR importing MeasureTool: {e}")

# Import MarkerDialog
try:
    from .ui.marker_dialog import MarkerDialog
except Exception as e:
    _imports_ok = False
    _import_errors.append(('ui.marker_dialog.MarkerDialog', e, traceback.format_exc()))
    MarkerDialog = None
    print(f"ERROR importing MarkerDialog: {e}")

# Import CoordinateConverterDialog
try:
    from .ui.coordinate_converter_dialog import CoordinateConverterDialog
except Exception as e:
    _imports_ok = False
    _import_errors.append(('ui.coordinate_converter_dialog.CoordinateConverterDialog', e, traceback.format_exc()))
    CoordinateConverterDialog = None
    print(f"ERROR importing CoordinateConverterDialog: {e}")


class MissionResumeDialog(BaseDialog):
    """
    Dialog to prompt user to resume a paused mission.

    Shows mission details and offers two options:
    - Resume Mission: Restore saved mission state
    - Start Fresh: Clear saved state and begin new mission

    Qt5/Qt6 Compatible: Uses BaseDialog for rendering workarounds.
    """

    def __init__(self, saved_state, parent=None):
        """
        Initialize mission resume dialog.

        Args:
            saved_state: Dictionary containing mission state data
                Required keys: 'name', 'start_time'
            parent: Parent widget (should be iface.mainWindow())
        """
        super().__init__(parent)
        self.saved_state = saved_state
        self.setWindowTitle("Resume Mission?")
        self.setModal(True)
        self.setMinimumWidth(400)

        self._setup_ui()

    def _setup_ui(self):
        """Build the dialog UI."""
        layout = QVBoxLayout()

        # Format start time for display
        try:
            start_time_display = self.saved_state['start_time'][:19].replace('T', ' ')
        except (IndexError, KeyError):
            start_time_display = self.saved_state.get('start_time', 'Unknown')

        # Message label
        message = QLabel(
            f"<b>Found paused mission:</b><br><br>"
            f"Mission: {self.saved_state.get('name', 'Unknown')}<br>"
            f"Started: {start_time_display}<br><br>"
            f"Do you want to resume this mission?"
        )
        message.setWordWrap(True)
        layout.addWidget(message)

        # Buttons
        button_layout = QHBoxLayout()

        resume_button = QPushButton("Resume Mission")
        resume_button.setDefault(True)
        resume_button.clicked.connect(self.accept)
        button_layout.addWidget(resume_button)

        cancel_button = QPushButton("Start Fresh")
        cancel_button.clicked.connect(self.reject)
        button_layout.addWidget(cancel_button)

        layout.addLayout(button_layout)

        # Apply layout (triggers BaseDialog workarounds)
        self.setLayout(layout)


class ImportFailureDialog(BaseDialog):
    """
    Dialog to display import failure details when plugin fails to load.

    Shows detailed error information in a scrollable text area to help
    users diagnose and report plugin initialization problems.

    Qt5/Qt6 Compatible: Uses BaseDialog for rendering workarounds.
    """

    def __init__(self, error_summary, parent=None):
        """
        Initialize import failure dialog.

        Args:
            error_summary: Formatted string containing error details
            parent: Parent widget (should be iface.mainWindow())
        """
        super().__init__(parent)
        self.error_summary = error_summary
        self.setWindowTitle("SAR Tracker - Import Failure")
        self.setMinimumSize(700, 500)

        self._setup_ui()

    def _setup_ui(self):
        """Build the dialog UI."""
        from qgis.PyQt.QtWidgets import QTextEdit

        layout = QVBoxLayout()

        # Scrollable text area for error details
        text_edit = QTextEdit()
        text_edit.setReadOnly(True)
        text_edit.setPlainText(self.error_summary)
        text_edit.setFont(QFont("Courier New", 9))
        layout.addWidget(text_edit)

        # Close button
        close_button = QPushButton("Close")
        close_button.clicked.connect(self.accept)
        layout.addWidget(close_button)

        # Apply layout (triggers BaseDialog workarounds)
        self.setLayout(layout)


class sartracker:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # Create centralized error handler (Issue #3)
        self.error_handler = ErrorHandler(self.iface.messageBar())

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        try:
            locale_value = QSettings().value('locale/userLocale')
            if locale_value and str(locale_value):
                locale = str(locale_value)[0:2]
            else:
                locale = 'en'
        except Exception:
            locale = 'en'  # Fallback to English if locale detection fails
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'sartracker_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&sartracker')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # Initialize SAR tracking components
        self.layers_controller = None
        self.provider = None
        self.provider_name = None  # Track which provider is active (e.g., 'csv', 'http_traccar')
        self.provider_config = None  # Track provider config for reconnection
        self.sar_panel = None
        self.marker_tool = None
        self.measure_tool = None
        self.line_tool = None
        self.range_ring_tool = None
        self.bearing_tool = None
        self.polygon_tool = None
        self.tool_registry = None
        self.task_manager = None  # Task lifecycle management (Issue #6)
        self.current_marker_type = None  # 'poi' or 'casualty'
        self.coords_label = None  # Status bar coordinate display
        self.last_coords_point = None  # Last mouse position (for throttling)
        self.coords_update_timer = None  # Timer to throttle coordinate updates
        self._map_canvas_connection = None  # Track xyCoordinates signal connection (Issue #4)

        # Refresh state management (Issue #1: Prevent concurrent refreshes)
        self._refresh_in_progress = False
        self._current_refresh_task = None  # For backwards compatibility with Issue #4 cleanup

        # Coordinate systems
        self.wgs84 = QgsCoordinateReferenceSystem("EPSG:4326")
        self.itm = QgsCoordinateReferenceSystem("EPSG:29903")  # Irish Grid

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('sartracker', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # Version check
        from qgis.core import Qgis
        if Qgis.QGIS_VERSION_INT < 32800:  # 3.28.0
            warning(
                self.iface.messageBar(),
                "SAR Tracker",
                "This plugin is tested on QGIS 3.28-3.44. You have an older version - features may not work correctly.",
                duration=8
            )

        # Use absolute path to icon file
        icon_path = os.path.join(self.plugin_dir, 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'SAR Tracker Panel'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # Add separator for visual grouping
        separator = QAction(self.iface.mainWindow())
        separator.setSeparator(True)
        self.iface.addPluginToMenu(self.menu, separator)

        # Add Diagnostics menu item
        self.diagnostics_action = QAction("Diagnostics", self.iface.mainWindow())
        self.diagnostics_action.triggered.connect(self._show_diagnostics)
        self.iface.addPluginToMenu(self.menu, self.diagnostics_action)
        self.actions.append(self.diagnostics_action)

        # Add Smoke Test menu item
        self.smoketest_action = QAction("Run Smoke Test", self.iface.mainWindow())
        self.smoketest_action.triggered.connect(self._run_smoke_test)
        self.iface.addPluginToMenu(self.menu, self.smoketest_action)
        self.actions.append(self.smoketest_action)

        # ============================================================================
        # FAIL-FAST CHECK: Abort initialization if critical imports failed
        # ============================================================================
        # This MUST come AFTER Diagnostics and Smoke Test menus are added,
        # ensuring users can access diagnostic tools even when imports fail.
        #
        # If any imports failed during module loading, we display a clear error
        # message and abort initialization to prevent cryptic crashes later.
        if not _imports_ok:
            self._handle_import_failure(_import_errors)
            return  # Abort initialization - do not proceed with component setup

        # If we reach here, all imports succeeded and we can safely proceed
        # ============================================================================

        # will be set False in run()
        self.first_start = True

        # Initialize task manager for background operations (Issue #6 fix)
        from .utils.task_manager import TaskManager
        self.task_manager = TaskManager()

        # Initialize layers controller
        self.layers_controller = LayersController(self.iface)

        # Initialize marker map tool
        self.marker_tool = MarkerMapTool(self.iface.mapCanvas())
        self.marker_tool.marker_clicked.connect(self._on_marker_clicked)

        # Initialize measure tool
        self.measure_tool = MeasureTool(self.iface.mapCanvas())
        self.measure_tool.measurement_complete.connect(self._on_measurement_complete)

        # Initialize Line Tool (with error handling for late-binding import)
        try:
            from .maptools import LineTool
            self.line_tool = LineTool(self.iface.mapCanvas(), self.layers_controller)
            self.line_tool.drawing_complete.connect(self._on_line_complete)
            self.line_tool.drawing_cancelled.connect(self._on_drawing_cancelled)
            self.line_tool.drawing_error.connect(lambda e: self.error_handler.handle_exception(e, "Line drawing"))
        except Exception as e:
            self.line_tool = None
            warning(self.iface.messageBar(), "SAR Tracker",
                   f"Line Tool failed to load: {e}", duration=5)
            print(f"ERROR initializing LineTool: {e}")

        # Initialize Range Ring Tool (with error handling for late-binding import)
        try:
            from .maptools import RangeRingTool
            self.range_ring_tool = RangeRingTool(self.iface.mapCanvas(), self.layers_controller, self.iface)
            self.range_ring_tool.drawing_complete.connect(self._on_range_rings_complete)
            self.range_ring_tool.drawing_cancelled.connect(self._on_drawing_cancelled)
            self.range_ring_tool.drawing_error.connect(lambda e: self.error_handler.handle_exception(e, "Range ring"))
        except Exception as e:
            self.range_ring_tool = None
            warning(self.iface.messageBar(), "SAR Tracker",
                   f"Range Ring Tool failed to load: {e}", duration=5)
            print(f"ERROR initializing RangeRingTool: {e}")

        # Initialize Bearing Tool (with error handling for late-binding import)
        try:
            from .maptools import BearingTool
            self.bearing_tool = BearingTool(self.iface.mapCanvas(), self.layers_controller, self.iface)
            self.bearing_tool.drawing_complete.connect(self._on_bearing_complete)
            self.bearing_tool.drawing_cancelled.connect(self._on_drawing_cancelled)
            self.bearing_tool.drawing_error.connect(lambda e: self.error_handler.handle_exception(e, "Bearing line"))
        except Exception as e:
            self.bearing_tool = None
            warning(self.iface.messageBar(), "SAR Tracker",
                   f"Bearing Tool failed to load: {e}", duration=5)
            print(f"ERROR initializing BearingTool: {e}")

        # Initialize Polygon Tool (Search Areas) (with error handling for late-binding import)
        try:
            from .maptools import PolygonTool
            self.polygon_tool = PolygonTool(self.iface.mapCanvas(), self.layers_controller, self.iface)
            self.polygon_tool.drawing_complete.connect(self._on_polygon_complete)
            self.polygon_tool.drawing_cancelled.connect(self._on_drawing_cancelled)
            self.polygon_tool.drawing_error.connect(lambda e: self.error_handler.handle_exception(e, "Polygon drawing"))
        except Exception as e:
            self.polygon_tool = None
            warning(self.iface.messageBar(), "SAR Tracker",
                   f"Polygon Tool failed to load: {e}", duration=5)
            print(f"ERROR initializing PolygonTool: {e}")

        # Initialize Tool Registry (with error handling for late-binding import)
        try:
            from .maptools import ToolRegistry
            self.tool_registry = ToolRegistry(self.iface.mapCanvas(), self.iface)
            # Only register tools that successfully loaded
            if self.line_tool:
                self.tool_registry.register_tool('line', self.line_tool)
            if self.range_ring_tool:
                self.tool_registry.register_tool('range_rings', self.range_ring_tool)
            if self.bearing_tool:
                self.tool_registry.register_tool('bearing', self.bearing_tool)
            if self.polygon_tool:
                self.tool_registry.register_tool('polygon', self.polygon_tool)
            self.tool_registry.tool_activated.connect(self._on_tool_activated)
            self.tool_registry.tool_deactivated.connect(self._on_tool_deactivated)
        except Exception as e:
            self.tool_registry = None
            warning(self.iface.messageBar(), "SAR Tracker",
                   f"Tool Registry failed to load: {e}", duration=5)
            print(f"ERROR initializing ToolRegistry: {e}")

        # Initialize SAR Panel
        self.sar_panel = SARPanel(self.iface.mainWindow())
        self.iface.addDockWidget(RightDockWidgetArea, self.sar_panel)
        self.sar_panel.hide()  # Hidden by default

        # Connect SAR Panel signals
        self.sar_panel.mission_started.connect(self._on_mission_started)
        self.sar_panel.mission_paused.connect(self._on_mission_paused)
        self.sar_panel.mission_resumed.connect(self._on_mission_resumed)
        self.sar_panel.mission_finished.connect(self._on_mission_finished)
        self.sar_panel.refresh_requested.connect(self._on_refresh_data)
        self.sar_panel.csv_load_requested.connect(self._on_load_csv)
        self.sar_panel.add_poi_requested.connect(self._on_add_poi_requested)
        self.sar_panel.add_clue_requested.connect(self._on_add_clue_requested)
        self.sar_panel.add_casualty_requested.connect(self._on_add_casualty_requested)
        self.sar_panel.add_hazard_requested.connect(self._on_add_hazard_requested)
        self.sar_panel.line_tool_requested.connect(self._on_line_tool_requested)
        self.sar_panel.polygon_tool_requested.connect(self._on_polygon_tool_requested)
        self.sar_panel.range_rings_tool_requested.connect(self._on_range_rings_tool_requested)
        self.sar_panel.bearing_tool_requested.connect(self._on_bearing_tool_requested)
        self.sar_panel.coordinate_converter_requested.connect(self._on_coordinate_converter_requested)
        self.sar_panel.measure_distance_requested.connect(self._on_measure_distance_requested)
        self.sar_panel.autosave_requested.connect(self._on_autosave_requested)

        # Add coordinate display to status bar
        self.coords_label = QLabel()
        self.coords_label.setMinimumWidth(550)
        self.coords_label.setMaximumWidth(550)  # Fixed width prevents jitter

        # Use monospace font for stable width
        font = QFont("Courier New", 10)
        if not font.exactMatch():
            font = QFont("Monospace", 10)
        self.coords_label.setFont(font)

        self.coords_label.setStyleSheet("QLabel { padding: 2px 8px; background-color: #f0f0f0; }")
        self.iface.statusBarIface().addPermanentWidget(self.coords_label)

        # Set up timer to throttle coordinate updates (50ms = 20 updates/sec max)
        self.coords_update_timer = QTimer()
        self.coords_update_timer.timeout.connect(self._update_coords_display)
        self.coords_update_timer.start(50)

        # Connect to map canvas mouse movement (stores point, actual update happens on timer)
        # Store connection reference for proper cleanup in unload() (Issue #4)
        self._map_canvas_connection = self.iface.mapCanvas().xyCoordinates.connect(self._on_mouse_move)

        # Check for paused mission and prompt to resume
        QTimer.singleShot(1000, self._check_for_paused_mission)  # Delay 1s to let QGIS fully load

    def _handle_import_failure(self, errors):
        """
        Handle import failures with clear user guidance.

        This method is called from initGui() if any critical imports failed during
        module loading. It displays both a persistent message bar warning and a
        detailed modal dialog to help users diagnose and resolve the issue.

        Args:
            errors: List of (module_name, exception, traceback) tuples

        Qt5/Qt6 Compatible: Uses utils.notify helpers and BaseDialog
        """
        # Show persistent message bar warning
        error(
            self.iface.messageBar(),
            "SAR Tracker - Critical Error",
            "Plugin failed to load due to import errors. Check the dialog for details.",
            duration=0  # Persistent - stays until user dismisses
        )

        # Build detailed error message
        error_summary = "SAR Tracker failed to load due to the following import errors:\n\n"

        for module_name, exc, tb in errors:
            error_summary += f"❌ Module: {module_name}\n"
            error_summary += f"   Error: {type(exc).__name__}: {exc}\n\n"

        error_summary += "\n" + "="*70 + "\n"
        error_summary += "SUGGESTED ACTIONS:\n"
        error_summary += "="*70 + "\n\n"
        error_summary += "1. Verify all plugin files are present and not corrupted\n"
        error_summary += "2. Run Diagnostics: Plugins > SAR Tracker > Diagnostics\n"
        error_summary += "3. Run Smoke Test: Plugins > SAR Tracker > Run Smoke Test\n"
        error_summary += "4. Try reinstalling the plugin\n"
        error_summary += "5. Check QGIS Python console for additional details\n"
        error_summary += "6. Ensure you have compatible QGIS version (3.28+)\n\n"
        error_summary += "="*70 + "\n"
        error_summary += "TECHNICAL DETAILS (first error):\n"
        error_summary += "="*70 + "\n\n"
        error_summary += errors[0][2]  # Include full traceback of first error

        # Show import failure dialog using BaseDialog (Issue #2 fix)
        dialog = ImportFailureDialog(error_summary, parent=self.iface.mainWindow())
        dialog_exec(dialog)

    def _show_diagnostics(self):
        """Show diagnostics dialog with error handling."""
        try:
            from .ui.diagnostics_panel import DiagnosticsPanel
            from .utils.qt_compat import dialog_exec
            dialog = DiagnosticsPanel(self.iface.mainWindow())
            dialog_exec(dialog)
        except Exception as e:
            error(
                self.iface.messageBar(),
                "SAR Tracker",
                f"Failed to load Diagnostics panel: {e}",
                duration=5
            )
            print(f"ERROR loading DiagnosticsPanel: {e}")
            print(traceback.format_exc())

    def _run_smoke_test(self):
        """Run smoke test with error handling."""
        try:
            from .tools.smoketest import run_smoke_test
            run_smoke_test(self.iface)
        except Exception as e:
            error(
                self.iface.messageBar(),
                "SAR Tracker",
                f"Failed to run Smoke Test: {e}",
                duration=5
            )
            print(f"ERROR running smoke test: {e}")
            print(traceback.format_exc())

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        try:
            # ============================================================
            # CRITICAL: Disconnect signals FIRST (Issue #4 fix)
            # Do this BEFORE cleaning up widgets to prevent handlers from
            # running while we're in the middle of cleanup
            # ============================================================

            # Disconnect map canvas mouse move signal
            if self._map_canvas_connection is not None:
                try:
                    self.iface.mapCanvas().xyCoordinates.disconnect(self._on_mouse_move)
                    print("[SARTRACKER] xyCoordinates signal disconnected successfully")
                except (TypeError, RuntimeError) as e:
                    # TypeError: Signal not connected (initGui never completed)
                    # RuntimeError: C++ object already deleted
                    print(f"[SARTRACKER] Warning: Could not disconnect xyCoordinates: {e}")
                self._map_canvas_connection = None

            # Cancel all background tasks (Issue #6 fix)
            # TaskManager handles:
            # - Signal disconnection BEFORE cancellation
            # - Task cancellation
            # - Cleanup of all active tasks
            if self.task_manager:
                try:
                    active_count = self.task_manager.get_active_count()
                    if active_count > 0:
                        print(f"[SARTRACKER] Cancelling {active_count} active task(s)...")
                        self.task_manager.cancel_all()
                        print("[SARTRACKER] All tasks cancelled successfully")
                except Exception as e:
                    print(f"[SARTRACKER] Warning: TaskManager cleanup error: {e}")
                finally:
                    self.task_manager = None

            # Legacy cleanup (for backwards compatibility if TaskManager not initialized)
            if self._current_refresh_task:
                try:
                    # Disconnect signals BEFORE canceling
                    try:
                        self._current_refresh_task.taskCompleted.disconnect()
                    except TypeError:
                        pass
                    try:
                        self._current_refresh_task.taskTerminated.disconnect()
                    except TypeError:
                        pass
                    self._current_refresh_task.cancel()
                except Exception as e:
                    print(f"[SARTRACKER] Warning: Legacy task cleanup error: {e}")
                finally:
                    self._current_refresh_task = None

            self._refresh_in_progress = False

            # Remove menu items and toolbar icons
            for action in self.actions:
                self.iface.removePluginMenu(
                    self.tr(u'&sartracker'),
                    action)
                self.iface.removeToolBarIcon(action)

            # Stop coordinate update timer
            if self.coords_update_timer:
                try:
                    self.coords_update_timer.stop()
                    self.coords_update_timer.deleteLater()
                except:
                    pass
                self.coords_update_timer = None

            # Remove coordinate label from status bar
            if self.coords_label:
                try:
                    self.iface.statusBarIface().removeWidget(self.coords_label)
                    self.coords_label.deleteLater()
                except:
                    pass
                self.coords_label = None

            # Deactivate and clean up all map tools
            if self.tool_registry:
                try:
                    self.tool_registry.deactivate_current()
                except:
                    pass

            # Clean up individual tools
            for tool_attr in ['marker_tool', 'measure_tool', 'line_tool', 'range_ring_tool', 'bearing_tool', 'polygon_tool']:
                tool = getattr(self, tool_attr, None)
                if tool:
                    try:
                        # Deactivate if it's the current tool
                        if self.iface.mapCanvas().mapTool() == tool:
                            self.iface.mapCanvas().unsetMapTool(tool)
                        # Call deactivate method if exists
                        if hasattr(tool, 'deactivate'):
                            tool.deactivate()
                        # Delete the tool
                        tool.deleteLater()
                    except:
                        pass
                    setattr(self, tool_attr, None)

            # Clean up tool registry
            if self.tool_registry:
                try:
                    self.tool_registry.deleteLater()
                except:
                    pass
                self.tool_registry = None

            # Disconnect and clean up SAR Panel
            if self.sar_panel:
                # Stop all timers BEFORE disconnecting signals (Issue #5 fix)
                try:
                    if hasattr(self.sar_panel, 'cleanup'):
                        self.sar_panel.cleanup()
                except Exception as e:
                    print(f"[SARTRACKER] Warning: Error during SARPanel cleanup: {e}")

                try:
                    # Disconnect all signals
                    self.sar_panel.mission_started.disconnect()
                    self.sar_panel.mission_paused.disconnect()
                    self.sar_panel.mission_resumed.disconnect()
                    self.sar_panel.mission_finished.disconnect()
                    self.sar_panel.refresh_requested.disconnect()
                    self.sar_panel.csv_load_requested.disconnect()
                    self.sar_panel.add_poi_requested.disconnect()
                    self.sar_panel.add_casualty_requested.disconnect()
                    self.sar_panel.add_hazard_requested.disconnect()
                    self.sar_panel.line_tool_requested.disconnect()
                    self.sar_panel.range_rings_tool_requested.disconnect()
                    self.sar_panel.coordinate_converter_requested.disconnect()
                    self.sar_panel.measure_distance_requested.disconnect()
                    self.sar_panel.autosave_requested.disconnect()
                except:
                    pass  # Signals may not be connected

                try:
                    # Remove from dock widget area
                    self.iface.removeDockWidget(self.sar_panel)
                    # Delete the panel
                    self.sar_panel.deleteLater()
                except:
                    pass
                self.sar_panel = None

            # Clean up layers controller
            if self.layers_controller:
                try:
                    self.layers_controller = None
                except:
                    pass

            # Clean up provider
            if self.provider:
                try:
                    self.provider = None
                except:
                    pass

        except Exception as e:
            print(f"Error during plugin unload: {e}")
            import traceback
            traceback.print_exc()


    def run(self):
        """Toggle SAR Tracker panel visibility"""
        if self.sar_panel.isVisible():
            self.sar_panel.hide()
        else:
            self.sar_panel.show()

    def _on_mission_started(self, mission_name):
        """Handle mission start."""
        print(f"Mission started: {mission_name}")
        success(
            self.iface.messageBar(),
            "SAR Tracker",
            f"Mission '{mission_name}' started",
            duration=3
        )

    def _on_mission_paused(self):
        """Handle mission pause."""
        print("Mission paused")
        warning(
            self.iface.messageBar(),
            "SAR Tracker",
            "Mission paused",
            duration=2
        )

    def _on_mission_resumed(self):
        """Handle mission resume."""
        print("Mission resumed")
        success(
            self.iface.messageBar(),
            "SAR Tracker",
            "Mission resumed",
            duration=2
        )

    def _on_mission_finished(self):
        """Handle mission finish."""
        print("Mission finished")
        success(
            self.iface.messageBar(),
            "SAR Tracker",
            "Mission finished",
            duration=3
        )

    def _on_refresh_data(self):
        """
        Handle data refresh request using background task.

        This method now uses QgsTask to parse CSVs in a background thread,
        preventing UI freezes during refresh operations. Includes concurrent
        refresh protection and proper error handling.

        Qt5/Qt6 Compatible: Uses QgsTask API which works identically in both versions.
        """
        if not self.provider:
            warning(
                self.iface.messageBar(),
                "SAR Tracker",
                "No data source loaded. Please load a data source first.",
                duration=3
            )
            return

        # Concurrent refresh protection (Issue #1)
        if self._refresh_in_progress:
            warning(
                self.iface.messageBar(),
                "SAR Tracker",
                "Refresh already in progress, please wait...",
                duration=2
            )
            return

        try:
            # Set refresh flag
            self._refresh_in_progress = True

            # Show loading state in UI
            if self.sar_panel:
                self.sar_panel.set_loading_state(True)

            # Create provider-specific background task
            task = self.provider.create_refresh_task("Refreshing tracking data")

            # Start task with managed lifecycle (Issue #6 fix)
            # TaskManager handles:
            # - Signal connection
            # - Automatic cleanup after completion
            # - Safe cancellation
            task_id = self.task_manager.start_task(
                task=task,
                on_complete=self._on_refresh_complete,
                on_error=self._on_refresh_error,
                task_id="refresh"
            )

            # Store task reference for backwards compatibility with Issue #4 cleanup
            self._current_refresh_task = task

        except Exception as e:
            # Reset state on setup error
            self._refresh_in_progress = False
            if self.sar_panel:
                self.sar_panel.set_loading_state(False)

            error(
                self.iface.messageBar(),
                "Refresh Error",
                f"Failed to start refresh: {str(e)}",
                duration=5
            )

    def _on_refresh_complete(self, task):
        """
        Handle successful refresh completion (runs in main thread).

        Args:
            task: Completed ProviderRefreshTask with results

        SAFETY: May be called after plugin unload if signal disconnect failed
        or task completed during unload. Check component existence.
        """
        # CRITICAL GUARD: Check if plugin components still exist
        if not self.layers_controller or not self.sar_panel:
            print("[SARTRACKER] Refresh completed after plugin unload, ignoring results")
            return

        try:
            # Reset refresh state
            self._refresh_in_progress = False
            self._current_refresh_task = None

            # Hide loading state (check again before accessing)
            if self.sar_panel:
                self.sar_panel.set_loading_state(False)

            # Check if task was cancelled
            if task.isCanceled():
                info(
                    self.iface.messageBar(),
                    "SAR Tracker",
                    "Refresh cancelled",
                    duration=2
                )
                return

            # Get results from background task
            if not task.results:
                warning(
                    self.iface.messageBar(),
                    "SAR Tracker",
                    "Refresh completed but no data returned",
                    duration=3
                )
                return

            results = task.results
            current = results.get('current', [])
            breadcrumbs = results.get('breadcrumbs', [])
            devices = results.get('devices', [])

            # Update layers (main thread operation)
            if current:
                self.layers_controller.update_current_positions(current)

            if breadcrumbs:
                self.layers_controller.update_breadcrumbs(breadcrumbs)

            # Update device list in panel
            if self.sar_panel:
                self.sar_panel.update_devices(devices)

            # Show success message
            success(
                self.iface.messageBar(),
                "SAR Tracker",
                f"Refreshed: {len(current)} devices, {len(breadcrumbs)} points",
                duration=2
            )

        except Exception as e:
            # Reset state on processing error
            self._refresh_in_progress = False
            if self.sar_panel:
                self.sar_panel.set_loading_state(False)

            error(
                self.iface.messageBar(),
                "Refresh Error",
                f"Error processing refresh results: {str(e)}",
                duration=5
            )

    def _on_refresh_error(self, task):
        """
        Handle refresh task error or termination (runs in main thread).

        Args:
            task: Failed or terminated ProviderRefreshTask

        SAFETY: May be called after plugin unload if signal disconnect failed
        or task terminated during unload. Check component existence.
        """
        # CRITICAL GUARD: Check if plugin components still exist
        if not self.sar_panel:
            print("[SARTRACKER] Refresh error after plugin unload, ignoring")
            return

        try:
            # Reset refresh state
            self._refresh_in_progress = False
            self._current_refresh_task = None

            # Hide loading state
            if self.sar_panel:
                self.sar_panel.set_loading_state(False)

            # Show error message
            error_msg = task.error_message if task.error_message else "Unknown error during refresh"
            error(
                self.iface.messageBar(),
                "Refresh Failed",
                f"Error refreshing data: {error_msg}",
                duration=5
            )

        except Exception as e:
            # DEFENSIVE: Catch ALL exceptions to prevent crashes in error handler
            print(f"[SARTRACKER] Exception in _on_refresh_error: {e}")
            import traceback
            traceback.print_exc()

            # Reset state (safe even if components are None)
            self._refresh_in_progress = False

            # Try to update UI, but don't crash if components are gone
            try:
                if self.sar_panel:
                    self.sar_panel.set_loading_state(False)
            except:
                pass

    def _load_provider(self, provider_name: str, config: dict):
        """
        Load and initialize a data provider via registry.

        This method provides a provider-agnostic way to load data sources,
        supporting CSV, HTTP, PostGIS, and future providers without code changes.

        CRITICAL FOR LIFE-SAFETY: This must handle errors gracefully and never
        leave the plugin in an inconsistent state.

        Args:
            provider_name: Name of provider (e.g., 'csv', 'http_traccar')
            config: Provider-specific configuration dict

        Qt5/Qt6 Compatible: Uses provider registry pattern.
        """
        # Prevent concurrent operations
        if self._refresh_in_progress:
            warning(
                self.iface.messageBar(),
                "SAR Tracker",
                "Please wait for current operation to complete",
                duration=2
            )
            return

        try:
            # Create provider via registry
            self.provider = provider_registry.get_provider(provider_name, config)
            self.provider_name = provider_name
            self.provider_config = config

            # Test connection (quick synchronous check)
            if not self.provider.test_connection():
                error(
                    self.iface.messageBar(),
                    "Connection Error",
                    f"Could not connect to {provider_name} data source",
                    duration=5
                )
                self.provider = None
                self.provider_name = None
                self.provider_config = None
                return

            # Update data source label with provider-specific info
            metadata = next(
                (m for m in provider_registry.list_providers() if m.name == provider_name),
                None
            )
            display_name = metadata.display_name if metadata else provider_name

            # Generate appropriate label based on provider type
            if provider_name == 'csv':
                import os
                csv_path = config['csv_path']
                if os.path.isdir(csv_path):
                    label = f"{display_name}: {os.path.basename(csv_path)}"
                else:
                    label = f"{display_name}: {os.path.basename(csv_path)}"
            else:
                # Generic label for other providers
                label = display_name

            self.sar_panel.set_data_source(label)

            # Set loading state
            self._refresh_in_progress = True
            if self.sar_panel:
                self.sar_panel.set_loading_state(True)

            info(
                self.iface.messageBar(),
                "SAR Tracker",
                f"Loading data from {display_name}...",
                duration=2
            )

            # Create provider-specific background task
            task = self.provider.create_refresh_task("Loading tracking data")

            # Start task with managed lifecycle (Issue #6 fix)
            # TaskManager handles:
            # - Signal connection
            # - Automatic cleanup after completion
            # - Safe cancellation
            task_id = self.task_manager.start_task(
                task=task,
                on_complete=self._on_load_complete,
                on_error=self._on_refresh_error,
                task_id="load"
            )

            # Store task reference for backwards compatibility with Issue #4 cleanup
            self._current_refresh_task = task

        except Exception as e:
            # Reset state on error
            self._refresh_in_progress = False
            if self.sar_panel:
                self.sar_panel.set_loading_state(False)

            error(
                self.iface.messageBar(),
                "Error Loading Provider",
                f"Failed to load {provider_name}: {str(e)}",
                duration=5
            )

    def _on_load_csv(self, csv_file):
        """
        Handle CSV load request from panel.

        Delegates to _load_provider() for provider-agnostic loading.

        Args:
            csv_file: Path to CSV file or folder
        """
        self._load_provider('csv', {'csv_path': csv_file})

    def _on_load_complete(self, task):
        """
        Handle provider load completion (runs in main thread).

        Args:
            task: Completed ProviderRefreshTask with results

        SAFETY: May be called after plugin unload if signal disconnect failed
        or task completed during unload. Check component existence.
        """
        # CRITICAL GUARD: Check if plugin components still exist
        if not self.layers_controller or not self.sar_panel:
            print("[SARTRACKER] Load completed after plugin unload, ignoring results")
            return

        try:
            # Reset refresh state
            self._refresh_in_progress = False
            self._current_refresh_task = None

            # Hide loading state (check again before accessing)
            if self.sar_panel:
                self.sar_panel.set_loading_state(False)

            # Check if task was cancelled
            if task.isCanceled():
                info(
                    self.iface.messageBar(),
                    "SAR Tracker",
                    "Load cancelled",
                    duration=2
                )
                return

            # Get results from background task
            if not task.results:
                warning(
                    self.iface.messageBar(),
                    "No Data",
                    "CSV file contains no valid tracking data",
                    duration=3
                )
                return

            results = task.results
            current = results.get('current', [])
            breadcrumbs = results.get('breadcrumbs', [])
            devices = results.get('devices', [])

            # Update layers (main thread operation)
            if current:
                self.layers_controller.update_current_positions(current)

            if breadcrumbs:
                self.layers_controller.update_breadcrumbs(breadcrumbs)

            # Update device list in panel
            if self.sar_panel:
                self.sar_panel.update_devices(devices)

            # Show result
            if not current and not breadcrumbs:
                info(
                    self.iface.messageBar(),
                    "No Data",
                    "CSV file contains no valid tracking data",
                    duration=3
                )
            else:
                success(
                    self.iface.messageBar(),
                    "SAR Tracker",
                    f"Loaded {len(current)} device(s), {len(breadcrumbs)} points",
                    duration=3
                )

        except Exception as e:
            # Reset state on processing error
            self._refresh_in_progress = False
            if self.sar_panel:
                self.sar_panel.set_loading_state(False)

            error(
                self.iface.messageBar(),
                "Error Loading CSV",
                f"Error processing CSV data: {str(e)}",
                duration=5
            )

    def _on_mouse_move(self, point):
        """
        Handle mouse movement over map canvas.
        Just store the point - actual display update happens on timer.

        Args:
            point: QgsPointXY in map canvas CRS

        SAFETY: This handler may be called after plugin unload if signal
        disconnect failed. Check widget existence before processing.
        """
        # Defensive check: Ensure our widgets haven't been destroyed
        # This prevents crashes if disconnect failed or event arrived during unload
        if not self.coords_label or not self.coords_update_timer:
            # Plugin is being/has been unloaded, ignore event silently
            # (This is normal during unload, not an error condition)
            return

        # Safe to proceed - store point for timer-based update
        self.last_coords_point = point

    def _update_coords_display(self):
        """
        Update coordinate display in status bar.
        Called by timer to throttle updates.

        SAFETY: Timer may fire during unload or after widgets destroyed.
        Check existence before accessing Qt objects.
        """
        # Defensive checks
        if not self.coords_label or not self.last_coords_point:
            return

        try:
            # Get canvas CRS
            canvas_crs = self.iface.mapCanvas().mapSettings().destinationCrs()

            # Transform to WGS84
            transform_to_wgs84 = QgsCoordinateTransform(
                canvas_crs,
                self.wgs84,
                QgsProject.instance()
            )
            wgs84_point = transform_to_wgs84.transform(self.last_coords_point)

            # Transform to Irish Grid (ITM)
            transform_to_itm = QgsCoordinateTransform(
                canvas_crs,
                self.itm,
                QgsProject.instance()
            )
            itm_point = transform_to_itm.transform(self.last_coords_point)

            # Format display text with fixed-width formatting
            coords_text = (
                f"WGS84: {wgs84_point.y():9.6f}°N, {wgs84_point.x():10.6f}°E  |  "
                f"Irish Grid: E:{int(itm_point.x()):7d}  N:{int(itm_point.y()):7d}"
            )

            # Update label (may raise RuntimeError if widget C++ object destroyed)
            self.coords_label.setText(coords_text)

        except RuntimeError as e:
            # Qt C++ object has been deleted but Python wrapper still exists
            # This is expected during cleanup - mark widget as invalid
            print(f"[SARTRACKER] Coordinate label destroyed, stopping updates")
            self.coords_label = None
            return

        except Exception as e:
            # Log unexpected errors instead of silent pass
            # This helps diagnose real bugs vs normal cleanup issues
            print(f"[SARTRACKER] Warning: Error updating coordinates display: {e}")
            # Don't spam console - only log first occurrence
            if not hasattr(self, '_coords_error_logged'):
                import traceback
                print(traceback.format_exc())
                self._coords_error_logged = True

    def _on_add_poi_requested(self):
        """Handle Add IPP/LKP button click from SAR Panel."""
        # Deactivate any drawing tools first
        if self.tool_registry:
            self.tool_registry.deactivate_current()

        self.current_marker_type = 'ipp_lkp'
        self.iface.mapCanvas().setMapTool(self.marker_tool)
        info(
            self.iface.messageBar(),
            "SAR Tracker",
            "Click on map to add IPP/LKP location",
            duration=3
        )

    def _on_add_clue_requested(self):
        """Handle Add Clue button click from SAR Panel."""
        # Deactivate any drawing tools first
        if self.tool_registry:
            self.tool_registry.deactivate_current()

        self.current_marker_type = 'clue'
        self.iface.mapCanvas().setMapTool(self.marker_tool)
        info(
            self.iface.messageBar(),
            "SAR Tracker",
            "Click on map to add Clue location",
            duration=3
        )

    def _on_add_casualty_requested(self):
        """Handle Add Casualty button click from SAR Panel."""
        # Deactivate any drawing tools first
        if self.tool_registry:
            self.tool_registry.deactivate_current()

        self.current_marker_type = 'casualty'
        self.iface.mapCanvas().setMapTool(self.marker_tool)
        info(
            self.iface.messageBar(),
            "SAR Tracker - CRITICAL",
            "Click on map to add Casualty location (found injured/deceased person)",
            duration=5
        )

    def _on_add_hazard_requested(self):
        """Handle Add Hazard button click from SAR Panel."""
        # Deactivate any drawing tools first
        if self.tool_registry:
            self.tool_registry.deactivate_current()

        self.current_marker_type = 'hazard'
        self.iface.mapCanvas().setMapTool(self.marker_tool)
        info(
            self.iface.messageBar(),
            "SAR Tracker",
            "Click on map to add Hazard location",
            duration=3
        )

    def _on_marker_clicked(self, lat, lon, easting, northing):
        """
        Handle map click from MarkerMapTool.

        Args:
            lat: Latitude (WGS84)
            lon: Longitude (WGS84)
            easting: Irish Grid Easting (ITM)
            northing: Irish Grid Northing (ITM)
        """
        # Show marker dialog
        dialog = MarkerDialog(lat, lon, easting, northing, self.iface.mainWindow())

        # Pre-select marker type based on which button was clicked
        if self.current_marker_type == 'clue':
            dialog.clue_radio.setChecked(True)
        elif self.current_marker_type == 'hazard':
            dialog.hazard_radio.setChecked(True)
        elif self.current_marker_type == 'casualty':
            dialog.casualty_radio.setChecked(True)
        else:
            dialog.ipp_lkp_radio.setChecked(True)

        # Show dialog and wait for user
        result = dialog_exec(dialog)

        if result == DialogAccepted:
            # Get marker data from dialog
            marker_data = dialog.get_marker_data()

            try:
                # Add marker to map based on type
                if marker_data['type'] == 'ipp_lkp':
                    marker_id = self.layers_controller.add_ipp_lkp(
                        name=marker_data['name'],
                        lat=marker_data['lat'],
                        lon=marker_data['lon'],
                        subject_category=marker_data.get('subject_category', ''),
                        description=marker_data['description'],
                        irish_grid_e=marker_data['easting'],
                        irish_grid_n=marker_data['northing']
                    )
                    marker_type_str = "IPP/LKP"
                elif marker_data['type'] == 'clue':
                    marker_id = self.layers_controller.add_clue(
                        name=marker_data['name'],
                        lat=marker_data['lat'],
                        lon=marker_data['lon'],
                        clue_type=marker_data.get('clue_type', ''),
                        confidence=marker_data.get('confidence', 'Possible'),
                        description=marker_data['description'],
                        irish_grid_e=marker_data['easting'],
                        irish_grid_n=marker_data['northing']
                    )
                    marker_type_str = "Clue"
                elif marker_data['type'] == 'casualty':
                    marker_id = self.layers_controller.add_casualty(
                        name=marker_data['name'],
                        lat=marker_data['lat'],
                        lon=marker_data['lon'],
                        condition=marker_data.get('condition', ''),
                        treatment=marker_data.get('treatment', ''),
                        evacuation_priority=marker_data.get('evacuation_priority', ''),
                        description=marker_data['description'],
                        found_by=marker_data.get('found_by', ''),
                        irish_grid_e=marker_data['easting'],
                        irish_grid_n=marker_data['northing']
                    )
                    marker_type_str = "Casualty"
                else:  # hazard
                    marker_id = self.layers_controller.add_hazard(
                        name=marker_data['name'],
                        lat=marker_data['lat'],
                        lon=marker_data['lon'],
                        hazard_type=marker_data.get('hazard_type', ''),
                        severity="Medium",  # Default severity
                        description=marker_data['description'],
                        irish_grid_e=marker_data['easting'],
                        irish_grid_n=marker_data['northing']
                    )
                    marker_type_str = "Hazard"

                success(
                    self.iface.messageBar(),
                    "SAR Tracker",
                    f"{marker_type_str} '{marker_data['name']}' added successfully",
                    duration=3
                )

            except Exception as e:
                QMessageBox.critical(
                    self.iface.mainWindow(),
                    "Error Adding Marker",
                    f"An error occurred while adding the marker:\n\n{str(e)}"
                )

        # Deactivate marker tool (return to pan/zoom)
        self.iface.mapCanvas().unsetMapTool(self.marker_tool)
        self.current_marker_type = None

    def _on_coordinate_converter_requested(self):
        """Handle Coordinate Converter button click."""
        dialog = CoordinateConverterDialog(self.iface.mainWindow())

        # Connect go_to_location signal
        dialog.go_to_location.connect(self._zoom_to_location)

        dialog_exec(dialog)

    def _zoom_to_location(self, lat, lon):
        """
        Zoom map to specified location.

        Args:
            lat: Latitude (WGS84)
            lon: Longitude (WGS84)
        """
        # Create a small extent around the point
        point = QgsPointXY(lon, lat)

        # Get canvas CRS
        canvas_crs = self.iface.mapCanvas().mapSettings().destinationCrs()

        # Transform point to canvas CRS if needed
        if canvas_crs.authid() != "EPSG:4326":
            transform = QgsCoordinateTransform(
                self.wgs84,
                canvas_crs,
                QgsProject.instance()
            )
            point = transform.transform(point)

        # Create extent (about 500m radius in map units)
        extent_size = 500  # meters
        if canvas_crs.isGeographic():
            # For geographic CRS, use degrees (rough approximation)
            extent_size = 0.005  # about 500m at this latitude

        extent = QgsRectangle(
            point.x() - extent_size,
            point.y() - extent_size,
            point.x() + extent_size,
            point.y() + extent_size
        )

        # Set map extent and refresh
        self.iface.mapCanvas().setExtent(extent)
        self.iface.mapCanvas().refresh()

    def _on_measure_distance_requested(self):
        """Handle Measure Distance & Bearing button click."""
        self.iface.mapCanvas().setMapTool(self.measure_tool)
        info(
            self.iface.messageBar(),
            "SAR Tracker",
            "Click two points on the map to measure distance and bearing",
            duration=5
        )

    def _on_line_tool_requested(self):
        """Handle Line Tool button click."""
        print(f"[SARTRACKER] _on_line_tool_requested() called")
        print(f"[SARTRACKER] Current canvas tool before activation: {self.iface.mapCanvas().mapTool()}")
        print(f"[SARTRACKER] Current active tool name: {self.tool_registry.get_active_tool_name()}")
        self.tool_registry.activate_tool('line')
        print(f"[SARTRACKER] Line tool activation complete")
        print(f"[SARTRACKER] Canvas tool after activation: {self.iface.mapCanvas().mapTool()}")
        info(
            self.iface.messageBar(),
            "SAR Tracker",
            "Click to add points. Right-click or ESC to finish line.",
            duration=5
        )

    def _on_polygon_tool_requested(self):
        """Handle Polygon Tool (Search Area) button click."""
        print(f"[SARTRACKER] _on_polygon_tool_requested() called")
        print(f"[SARTRACKER] Current canvas tool before activation: {self.iface.mapCanvas().mapTool()}")
        print(f"[SARTRACKER] Current active tool name: {self.tool_registry.get_active_tool_name()}")
        self.tool_registry.activate_tool('polygon')
        print(f"[SARTRACKER] Polygon tool activation complete")
        print(f"[SARTRACKER] Canvas tool after activation: {self.iface.mapCanvas().mapTool()}")
        info(
            self.iface.messageBar(),
            "SAR Tracker",
            "Search Area Tool: Click to add vertices (min 3). Right-click to finish and configure area.",
            duration=5
        )

    def _on_range_rings_tool_requested(self):
        """Handle Range Rings Tool button click."""
        self.tool_registry.activate_tool('range_rings')
        info(
            self.iface.messageBar(),
            "SAR Tracker",
            "Range Rings Tool: Click center point to configure rings",
            duration=5
        )

    def _on_bearing_tool_requested(self):
        """Handle Bearing Tool button click."""
        self.tool_registry.activate_tool('bearing')
        info(
            self.iface.messageBar(),
            "SAR Tracker",
            "Bearing Line Tool: Click origin point to configure bearing and distance",
            duration=5
        )

    def _on_line_complete(self, feature_data):
        """
        Handle line drawing completion.

        Args:
            feature_data: Dict with line info (name, distance_m, points, etc.)
        """
        success(
            self.iface.messageBar(),
            "SAR Tracker",
            f"Line '{feature_data['name']}' added ({feature_data['points']} points, {feature_data['distance_m']:.0f}m)",
            duration=3
        )
        # Deactivate tool
        self.tool_registry.deactivate_current()

    def _on_range_rings_complete(self, feature_data):
        """
        Handle range rings drawing completion.

        Args:
            feature_data: Dict with ring info (count, mode, center, etc.)
        """
        mode_str = "LPB-based" if feature_data['mode'] == 'lpb' else "Manual"
        success(
            self.iface.messageBar(),
            "SAR Tracker",
            f"{mode_str} range rings created ({feature_data['count']} rings)",
            duration=3
        )
        # Deactivate tool
        self.tool_registry.deactivate_current()

    def _on_bearing_complete(self, feature_data):
        """
        Handle bearing line drawing completion.

        Args:
            feature_data: Dict with bearing line info (name, bearing, distance, etc.)
        """
        bearing_type = feature_data['bearing_type']
        success(
            self.iface.messageBar(),
            "SAR Tracker",
            f"Bearing Line '{feature_data['name']}' created ({feature_data['bearing']:.1f}° True, {feature_data['magnetic_bearing']:.1f}° Magnetic, {feature_data['distance_m']:.0f}m)",
            duration=3
        )
        # Deactivate tool
        self.tool_registry.deactivate_current()

    def _on_polygon_complete(self, feature_data):
        """
        Handle polygon (search area) drawing completion.

        Args:
            feature_data: Dict with search area info (name, team, status, priority, vertices, etc.)
        """
        success(
            self.iface.messageBar(),
            "SAR Tracker",
            f"Search Area '{feature_data['name']}' created ({feature_data['vertices']} vertices, {feature_data['priority']} priority, {feature_data['status']})",
            duration=3
        )

        # Deactivate tool via registry (standard pattern, same as other tools)
        self.tool_registry.deactivate_current()

    def _on_drawing_cancelled(self):
        """Handle drawing cancellation (ESC pressed or dialog cancelled)."""
        # Deactivate the current drawing tool
        self.tool_registry.deactivate_current()
        # Silent cancellation - no message needed

    def _on_tool_activated(self, tool_name):
        """
        Update UI when drawing tool activated.

        Args:
            tool_name: Name of activated tool
        """
        if hasattr(self, 'sar_panel') and self.sar_panel:
            self.sar_panel.set_active_tool(tool_name.title())

    def _on_tool_deactivated(self, tool_name):
        """
        Update UI when drawing tool deactivated.

        Args:
            tool_name: Name of deactivated tool
        """
        if hasattr(self, 'sar_panel') and self.sar_panel:
            self.sar_panel.set_active_tool("None")

    def _on_measurement_complete(self, distance_m, distance_km, bearing, point1, point2):
        """
        Handle measurement completion.

        Args:
            distance_m: Distance in meters
            distance_km: Distance in kilometers
            bearing: Bearing in degrees (0-360, where 0 = North)
            point1: First point
            point2: Second point
        """
        # Format distance nicely
        if distance_m < 1000:
            distance_str = f"{distance_m:.1f} meters"
        else:
            distance_str = f"{distance_km:.2f} km"

        # Format bearing with cardinal direction
        cardinal = self._bearing_to_cardinal(bearing)

        # Show results on single line for better visibility
        message = f"<b>Distance:</b> {distance_str}  •  <b>Bearing:</b> {bearing:.1f}° ({cardinal})"

        # Use message bar with longer duration
        success(
            self.iface.messageBar(),
            "Measurement Result",
            message,
            duration=10
        )

        # Deactivate tool (return to pan/zoom)
        self.iface.mapCanvas().unsetMapTool(self.measure_tool)

    def _bearing_to_cardinal(self, bearing):
        """
        Convert bearing to cardinal direction.

        Args:
            bearing: Bearing in degrees (0-360)

        Returns:
            str: Cardinal direction (N, NE, E, SE, S, SW, W, NW)
        """
        directions = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]
        index = int((bearing + 22.5) / 45) % 8
        return directions[index]

    def _on_autosave_requested(self):
        """Handle auto-save request from SAR Panel."""
        try:
            # Save the current QGIS project
            project = QgsProject.instance()

            # Check if project has a file path
            if project.fileName():
                # Project already has a file, save it
                save_success = project.write()

                if save_success:
                    self.sar_panel.update_autosave_status(True)
                    success(
                        self.iface.messageBar(),
                        "SAR Tracker",
                        "Project saved successfully",
                        duration=2
                    )
                else:
                    self.sar_panel.update_autosave_status(False)
                    error(
                        self.iface.messageBar(),
                        "SAR Tracker",
                        "Failed to save project",
                        duration=3
                    )
            else:
                # Project hasn't been saved yet - prompt for location
                file_path, _ = QFileDialog.getSaveFileName(
                    self.iface.mainWindow(),
                    "Save QGIS Project",
                    "",
                    "QGIS Project Files (*.qgz *.qgs)"
                )

                if file_path:
                    save_success = project.write(file_path)

                    if save_success:
                        self.sar_panel.update_autosave_status(True)
                        success(
                            self.iface.messageBar(),
                            "SAR Tracker",
                            f"Project saved to {file_path}",
                            duration=3
                        )
                    else:
                        self.sar_panel.update_autosave_status(False)
                else:
                    # User cancelled - don't mark as failed
                    pass

        except Exception as e:
            self.sar_panel.update_autosave_status(False)
            QMessageBox.critical(
                self.iface.mainWindow(),
                "Auto-Save Error",
                f"Error saving project:\n\n{str(e)}"
            )

    def _check_for_paused_mission(self):
        """Check if there's a paused mission and prompt user to resume."""
        try:
            saved_state = self.sar_panel.load_mission_state()

            if not saved_state:
                # No saved state or invalid state (already cleared)
                return

            # Show resume dialog using BaseDialog (Issue #2 fix)
            dialog = MissionResumeDialog(saved_state, parent=self.iface.mainWindow())
            result = dialog_exec(dialog)

            if result == DialogAccepted:
                # Attempt to resume the mission
                if self.sar_panel.restore_mission_state(saved_state):
                    self.sar_panel.show()  # Show panel
                    success(
                        self.iface.messageBar(),
                        "SAR Tracker",
                        f"Mission '{saved_state['name']}' resumed",
                        duration=3
                    )
                else:
                    # restore_mission_state() already showed error message
                    pass
            else:
                # User chose to start fresh - clear saved state
                self.sar_panel._clear_mission_state()

        except Exception as e:
            # Catch-all for any unexpected errors in the resume flow
            print(f"Unexpected error in mission resume: {e}")
            error(
                self.iface.messageBar(),
                "SAR Tracker",
                f"Error checking for paused mission: {e}",
                duration=5
            )
